SELECT A.ADRESAID, A.DRZAVAID, A.GRADID, A.ULICA, A.BROJ, G.NAZIVGRADA FROM ADRESA A LEFT JOIN GRAD G ON A.GRADID = G.GRADID;

SELECT A.ADRESAID, A.DRZAVAID, A.GRADID, A.ULICA, A.BROJ, G.NAZIVGRADA FROM ADRESA A 
LEFT JOIN GRAD G ON A.GRADID = G.GRADID LEFT JOIN DRZAVA D ON G.DRZAVAID = D.DRZAVAID;

SELECT * FROM DOBAVLJAC;

UPDATE Dobavljac 
SET nazivDobavljaca = 'Proba', telefon = '011252569', maticniBroj = '1235689', 
pib = PIBTip ('687650431'), adresaID = 1 
WHERE dobavljacID = 1;

UPDATE ARTIKAL SET NAZIV = 'Probaaaaa', PAKOVANJE = '5g', JMID = 1, STOPAID = 1, KVALITET = 20,
AKTUELNACENA = 600.21 WHERE ARTIKALID = 4;

SELECT * FROM CENAPARITET;

DELETE FROM CENAPARITET WHERE CENAPARITETID = 4;