CREATE TABLE RADNIK (
radnikID NUMBER,
imePrezime varchar2 (50),
telefon varchar2(15),
mejl varchar2(50),
CONSTRAINT PK_Radnik PRIMARY KEY (radnikID)
);

SELECT * FROM RADNIK;

CREATE TABLE JEDINICAMERE(
jmID NUMBER,
nazivJM varchar2(20),
CONSTRAINT PK_JedinicaMere PRIMARY KEY (jmID)
);

CREATE TABLE PORESKASTOPA (
stopaID NUMBER,
iznos DECIMAL(7,2),
datum DATE,
CONSTRAINT PK_PORESKASTOPA PRIMARY KEY (stopaID)
);

CREATE TABLE ARTIKAL (
artikalID NUMBER,
naziv varchar2(50),
pakovanje varchar2(20),
kvalitet varchar2(100),
jmID NUMBER,
stopaID NUMBER,
CONSTRAINT PK_ARTIKAL PRIMARY KEY (artikalID),
CONSTRAINT FK_ARTIKAL FOREIGN KEY (jmID) REFERENCES JEDINICAMERE (jmID),
FOREIGN KEY (stopaID) REFERENCES PORESKASTOPA (stopaID)
);

ALTER TABLE ARTIKAL
ADD (aktuelnaCena DECIMAL(15,2));

CREATE TABLE DRZAVA (
drzavaID NUMBER,
nazivDrzave varchar2(20),
CONSTRAINT PK_DRZAVA PRIMARY KEY (drzavaID)
);

CREATE TABLE GRAD (
drzavaID NUMBER,
gradID NUMBER,
nazivGrada varchar2(20),
CONSTRAINT PK_GRAD PRIMARY KEY (drzavaID, gradID),
CONSTRAINT FK_GRAD FOREIGN KEY (drzavaID) REFERENCES DRZAVA (drzavaID)
);

CREATE TABLE ADRESA (
adresaID NUMBER,
drzavaID NUMBER,
gradID NUMBER,
ulica varchar2(30),
broj NUMBER,
CONSTRAINT PK_ADRESA PRIMARY KEY (drzavaID, gradID, adresaID),
CONSTRAINT FK_ADRESA FOREIGN KEY (drzavaID, gradID) REFERENCES GRAD (drzavaID, gradID)
);

CREATE TABLE DOBAVLJAC (
dobavljacID NUMBER,
nazivDobavljaca varchar2(50),
telefon varchar2(15),
maticniBroj varchar2(13),
PIB varchar2(15),
adresaID NUMBER,
drzavaID NUMBER,
gradID NUMBER,
CONSTRAINT PK_DOBAVLJAC PRIMARY KEY (dobavljacID),
CONSTRAINT FK_DOBAVLJAC FOREIGN KEY (adresaID, drzavaID, gradID) REFERENCES ADRESA (adresaID, drzavaID, gradID)
);

ALTER TABLE Adresa
ADD (nazivGrada VARCHAR2(50));

CREATE TABLE PORUDZBENICA(
porudzbenicaID NUMBER,
datum DATE,
radnikID NUMBER,
dobavljacID NUMBER,
CONSTRAINT PK_PORUDZBENICA PRIMARY KEY (porudzbenicaID),
CONSTRAINT FK_PORUDZBENICA FOREIGN KEY (radnikID) REFERENCES RADNIK (radnikID),
FOREIGN KEY (dobavljacID) REFERENCES DOBAVLJAC (dobavljacID)
);

CREATE TABLE SKLADISTE (
skladisteID NUMBER,
nazivSkladista varchar2(50),
drzavaID NUMBER,
gradID NUMBER,
CONSTRAINT PK_SKLADISTE PRIMARY KEY (skladisteID),
CONSTRAINT FK_SKLADISTE FOREIGN KEY (drzavaID, gradID) REFERENCES GRAD (drzavaID, gradID)
);

CREATE TABLE OTPREMNICA(
brojOtpremnice NUMBER,
datumDokumenta DATE,
datumValute DATE,
sifraKomitenta NUMBER,
dobavljacID NUMBER,
porudzbenicaID NUMBER,
radnikID NUMBER,
CONSTRAINT PK_OTPREMNICA PRIMARY KEY (brojOtpremnice),
CONSTRAINT FK_OTPREMNICA FOREIGN KEY (dobavljacID) REFERENCES DOBAVLJAC (dobavljacID),
FOREIGN KEY (porudzbenicaID) REFERENCES PORUDZBENICA (porudzbenicaID),
FOREIGN KEY (radnikID) REFERENCES RADNIK (radnikID)
);

CREATE TABLE RACUN(
brojRacuna NUMBER,
datumRacuna DATE,
datumPlacanja DATE,
datumPrometa DATE,
dobavljacID NUMBER,
skladisteID NUMBER,
brojOtpremnice NUMBER,
radnikID NUMBER,
CONSTRAINT PK_RACUN PRIMARY KEY (brojRacuna),
CONSTRAINT FK_RACUN FOREIGN KEY (dobavljacID) REFERENCES DOBAVLJAC (dobavljacID),
FOREIGN KEY (skladisteID) REFERENCES SKLADISTE (skladisteID),
FOREIGN KEY (brojOtpremnice) REFERENCES OTPREMNICA (brojOtpremnice),
FOREIGN KEY (radnikID) REFERENCES RADNIK (radnikID)
);

ALTER TABLE RACUN
ADD CONSTRAINT FK_SSKLADISTEE
FOREIGN KEY (SKLADISTEID)
REFERENCES SKLADISTE(SKLADISTEID)
ON DELETE CASCADE;

ALTER TABLE RACUN
ADD (drzavaID NUMBER);

ALTER TABLE RACUN
ADD (gradID NUMBER);

ALTER TABLE RACUN
ADD (UKUPNO DECIMAL(15,2));

ALTER TABLE RACUN
ADD CONSTRAINT FK_RACUN2
FOREIGN KEY (drzavaID, gradID)
REFERENCES GRAD (drzavaID, gradID);

CREATE TABLE STAVKARACUNA (
brojRacuna NUMBER,
stavkaRacunaID NUMBER,
iznos DECIMAL(15,2),
kolicina NUMBER,
artikalID NUMBER,
CONSTRAINT PK_STAVKARACUNA PRIMARY KEY (brojRacuna, stavkaRacunaID),
CONSTRAINT FK_STAVKARACUNA FOREIGN KEY (artikalID) REFERENCES Artikal (artikalID)
);


ALTER TABLE OTPREMNICA
ADD (nazivDobavljaca varchar2(50));

ALTER TABLE ARTIKAL
DROP COLUMN KVALITET;

ALTER TABLE ARTIKAL
ADD (KVALITET NUMBER);